### PR TITLE
Lerna

### PR DESCRIPTION
**Pull request by petedavisdev**

### CODE REVIEW

**Comment by petedavisdev** [comment]
- Flatter folder structure
- Co-locate component frontend files within View layer of Features and Projects
- Named js imports and rename index files so that they are easier to identify
- Lerna - package.json per project with hoisted dependencies
- NPM scripts for build and lint (other scripts included for reference - non-working)
- Rollup and Babel - independent browserlist per project
- Global linting
- Update README

**Comment by Phoen1x84** [comment]
I pulled down this branch and run an ```npm install``` at the root directory where lerna is. I ran ```lerna run build``` but the build failed. The only way I could get this to work was to ```run npm i``` in each of the projects which gave me duplicated node_modules. Is this what should happen or have I missed something?

**Comment by petedavisdev** [comment]
Try `npm run build` not `lerna run build`. Take a look in the root package.json file to see what it does.

**Comment by Phoen1x84** [comment]
ok I was using the lerna command from the lerna docs, I can see the references in the node_modules under each project now with the reference in the root directory.

**Pull request closed without merging**
